-- Seed data for Currency table
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('THB','Thai Baht',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('CDF','Congolese Franc',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('HKD','Hong Kong Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('IDR','Indonesian Rupiah',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('TRY','Turkish Lira',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('ETB','Ethiopian Birr',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('ILS','Israeli Shekel',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MOP','Macanese Pataca',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SYP','Syrian Pound',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('AOA','Angolan Kwanza',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SCR','Seychellois Rupee',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MRU','Mauritanian Ouguiya',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('GTQ','Guatemalan Quetzal',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('HUF','Hungarian Forint',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MXN','Mexican Peso',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('CVE','Cape Verdean Escudo',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('RUB','Russian Ruble',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('JMD','Jamaican Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('AWG','Aruban Florin',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('ZAR','South African Rand',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SAR','Saudi Riyal',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BWP','Botswana Pula',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('TOP','Tongan Paʻanga',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MNT','Mongolian Tögrög',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('IRR','Iranian Rial',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('UYU','Uruguayan Peso',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('TTD','Trinidad and Tobago Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MYR','Malaysian Ringgit',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('ANG','Netherlands Antillean Guilder',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BND','Brunei Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BTN','Bhutanese Ngultrum',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('QAR','Qatari Riyal',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SHP','Saint Helena Pound',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('CUP','Cuban Peso',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BMD','Bermudian Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SDG','Sudanese Pound',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('LAK','Lao Kip',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('AED','UAE Dirham',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('CLP','Chilean Peso',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('RSD','Serbian Dinar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('KGS','Kyrgyzstani Som',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('KES','Kenyan Shilling',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('XPF','CFP Franc',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('AZN','Azerbaijani Manat',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('XCD','East Caribbean Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('AFN','Afghan Afghani',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('KPW','North Korean Won',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('ERN','Eritrean Nakfa',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('AUD','Australian Dollar',2,true,true,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('NOC','No Official Currency',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('NGN','Nigerian Naira',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BGN','Bulgarian Lev',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('TWD','Taiwan Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('LYD','Libyan Dinar',3,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('NPR','Nepalese Rupee',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('PLN','Polish Złoty',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('COP','Colombian Peso',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('CRC','Costa Rican Colón',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BHD','Bahraini Dinar',3,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('PKR','Pakistani Rupee',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('XOF','West African CFA Franc',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('GBP','British Pound Sterling',2,true,true,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('TND','Tunisian Dinar',3,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('OMR','Omani Rial',3,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MZN','Mozambican Metical',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('GYD','Guyanese Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('CZK','Czech Koruna',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MGA','Malagasy Ariary',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('DKK','Danish Krone',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('KYD','Cayman Islands Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('GIP','Gibraltar Pound',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MVR','Maldivian Rufiyaa',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SSP','South Sudanese Pound',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('RON','Romanian Leu',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('STN','São Tomé and Príncipe Dobra',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('RWF','Rwandan Franc',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('NAD','Namibian Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('JOD','Jordanian Dinar',3,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('VUV','Vanuatu Vatu',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BBD','Barbados Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('UAH','Ukrainian Hryvnia',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('CHF','Swiss Franc',2,true,true,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SOS','Somali Shilling',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('CAD','Canadian Dollar',2,true,true,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('GEL','Georgian Lari',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('LKR','Sri Lankan Rupee',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BOB','Boliviano',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MDL','Moldovan Leu',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('NZD','New Zealand Dollar',2,true,true,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MMK','Myanmar Kyat',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('LRD','Liberian Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('VND','Vietnam Dong',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('PGK','Papua New Guinean Kina',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('VES','Venezuelan Bolívar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('PYG','Paraguayan Guaraní',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BZD','Belize Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SRD','Surinamese Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SEK','Swedish Krona',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('DZD','Algerian Dinar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('ARS','Argentine Peso',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('KHR','Cambodian Riel',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('FJD','Fijian Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('PEN','Peruvian Sol',2,true,false,1) ON CONFLICT DO NOTHING;
insert into payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") values ('UZS','Uzbekistani Som',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('DJF','Djiboutian Franc',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BRL','Brazilian Real',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('HNL','Honduran Lempira',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('LBP','Lebanese Pound',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('EGP','Egyptian Pound',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('TJS','Tajikistani Somoni',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('USD','US Dollar',2,true,true,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('FKP','Falkland Islands Pound',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('TMT','Turkmenistani Manat',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('PHP','Philippine Peso',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('LSL','Lesotho Loti',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('ISK','Icelandic Króna',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('YER','Yemeni Rial',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SBD','Solomon Islands Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SLE','Sierra Leonean Leone',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MUR','Mauritian Rupee',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('CNY','Chinese Yuan',2,true,true,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('PAB','Panamanian Balboa',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BAM','Bosnia and Herzegovina Mark',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('NOK','Norwegian Krone',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('KMF','Comorian Franc',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BDT','Bangladeshi Taka',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('INR','Indian Rupee',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('HTG','Haitian Gourde',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('ALL','Albanian Lek',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MAD','Moroccan Dirham',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MWK','Malawian Kwacha',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('GMD','Gambian Dalasi',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('AMD','Armenian Dram',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('UGX','Ugandan Shilling',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('KRW','Korean Won',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('DOP','Dominican Peso',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('MKD','Macedonian Denar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('KWD','Kuwaiti Dinar',3,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('EUR','Euro',2,true,true,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('ZWL','Zimbabwean Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('TZS','Tanzanian Shilling',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BYN','Belarusian Ruble',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('ZMW','Zambian Kwacha',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('XAF','Central African CFA Franc',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('NIO','Nicaraguan Córdoba',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('KZT','Kazakhstani Tenge',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SGD','Singapore Dollar',2,true,true,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('JPY','Japanese Yen',0,true,true,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('IQD','Iraqi Dinar',3,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('WST','Samoan Tala',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BIF','Burundian Franc',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('GHS','Ghanaian Cedi',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SZL','Eswatini Lilangeni',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('BSD','Bahamian Dollar',2,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('GNF','Guinean Franc',0,true,false,1) ON CONFLICT DO NOTHING;
INSERT INTO payment."Currency" ("Code","Name","MinorUnit","IsActive","IsGlobal","Type") VALUES ('SVC','Salvadoran Colón',2,true,false,1) ON CONFLICT DO NOTHING;

-- Seed data for Country table
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (1, 'Afghanistan', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg', '93', 'AF','AFG', 'AFN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (2, 'Åland Islands', 'https://flagcdn.com/ax.svg', '358', 'AX', 'ALA', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (3, 'Albania', 'https://flagcdn.com/al.svg', '355', 'AL', 'ALB', 'ALL') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (4, 'Algeria', 'https://flagcdn.com/dz.svg', '213', 'DZ', 'DZA', 'DZD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (5, 'American Samoa', 'https://flagcdn.com/as.svg', '1', 'AS', 'ASM', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (6, 'Andorra', 'https://flagcdn.com/ad.svg', '376', 'AD', 'AND', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (7, 'Angola', 'https://flagcdn.com/ao.svg', '244', 'AO', 'AGO', 'AOA') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (8, 'Anguilla', 'https://flagcdn.com/ai.svg', '1', 'AI', 'AIA', 'XCD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (9, 'Antarctica', 'https://flagcdn.com/aq.svg', '672', 'AQ', 'ATA', 'NOC') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (10, 'Antigua and Barbuda', 'https://flagcdn.com/ag.svg', '1', 'AG', 'ATG', 'XCD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (11, 'Argentina', 'https://flagcdn.com/ar.svg', '54', 'AR', 'ARG', 'ARS') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (12, 'Armenia', 'https://flagcdn.com/am.svg', '374', 'AM', 'ARM', 'AMD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (13, 'Aruba', 'https://flagcdn.com/aw.svg', '297', 'AW', 'ABW', 'AWG') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (14, 'Australia', 'https://flagcdn.com/au.svg', '61', 'AU', 'AUS', 'AUD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (15, 'Austria', 'https://flagcdn.com/at.svg', '43', 'AT', 'AUT', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (16, 'Azerbaijan', 'https://flagcdn.com/az.svg', '994', 'AZ', 'AZE', 'AZN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (17, 'Bahamas', 'https://flagcdn.com/bs.svg', '1', 'BS', 'BHS', 'BSD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (18, 'Bahrain', 'https://flagcdn.com/bh.svg', '973', 'BH', 'BHR', 'BHD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (19, 'Bangladesh', 'https://flagcdn.com/bd.svg', '880', 'BD', 'BGD', 'BDT') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (20, 'Barbados', 'https://flagcdn.com/bb.svg', '1', 'BB', 'BRB', 'BBD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (21, 'Belarus', 'https://flagcdn.com/by.svg', '375', 'BY', 'BLR', 'BYN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (22, 'Belgium', 'https://flagcdn.com/be.svg', '32', 'BE', 'BEL', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (23, 'Belize', 'https://flagcdn.com/bz.svg', '501', 'BZ', 'BLZ', 'BZD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (24, 'Benin', 'https://flagcdn.com/bj.svg', '229', 'BJ', 'BEN', 'XOF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (25, 'Bermuda', 'https://flagcdn.com/bm.svg', '1', 'BM', 'BMU', 'BMD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (26, 'Bhutan', 'https://flagcdn.com/bt.svg', '975', 'BT', 'BTN', 'BTN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (27, 'Bolivia (Plurinational State of)', 'https://flagcdn.com/bo.svg', '591', 'BO', 'BOL', 'BOB') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (28, 'Bonaire, Sint Eustatius and Saba', 'https://flagcdn.com/bq.svg', '599', 'BQ', 'BES', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (29, 'Bosnia and Herzegovina', 'https://flagcdn.com/ba.svg', '387', 'BA', 'BIH', 'BAM') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (30, 'Botswana', 'https://flagcdn.com/bw.svg', '267', 'BW', 'BWA', 'BWP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (31, 'Bouvet Island', 'https://flagcdn.com/bv.svg', '47', 'BV', 'BVT', 'NOK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (32, 'Brazil', 'https://flagcdn.com/br.svg', '55', 'BR', 'BRA', 'BRL') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (33, 'British Indian Ocean Territory', 'https://flagcdn.com/io.svg', '246', 'IO', 'IOT', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (34, 'United States Minor Outlying Islands', 'https://flagcdn.com/um.svg', '246', 'UM', 'UMI', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (35, 'Virgin Islands (British)', 'https://flagcdn.com/vg.svg', '1', 'VG', 'VGB', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (36, 'Virgin Islands (U.S.)', 'https://flagcdn.com/vi.svg', '1 340', 'VI', 'VIR', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (37, 'Brunei Darussalam', 'https://flagcdn.com/bn.svg', '673', 'BN', 'BRN', 'BND') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (38, 'Bulgaria', 'https://flagcdn.com/bg.svg', '359', 'BG', 'BGR', 'BGN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (39, 'Burkina Faso', 'https://flagcdn.com/bf.svg', '226', 'BF', 'BFA', 'XOF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (40, 'Burundi', 'https://flagcdn.com/bi.svg', '257', 'BI', 'BDI', 'BIF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (41, 'Cambodia', 'https://flagcdn.com/kh.svg', '855', 'KH', 'KHM', 'KHR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (42, 'Cameroon', 'https://flagcdn.com/cm.svg', '237', 'CM', 'CMR', 'XAF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (43, 'Canada', 'https://flagcdn.com/ca.svg', '1', 'CA', 'CAN', 'CAD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (44, 'Cabo Verde', 'https://flagcdn.com/cv.svg', '238', 'CV', 'CPV', 'CVE') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (45, 'Cayman Islands', 'https://flagcdn.com/ky.svg', '1', 'KY', 'CYM', 'KYD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (46, 'Central African Republic', 'https://flagcdn.com/cf.svg', '236', 'CF', 'CAF', 'XAF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (47, 'Chad', 'https://flagcdn.com/td.svg', '235', 'TD', 'TCD', 'XAF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (48, 'Chile', 'https://flagcdn.com/cl.svg', '56', 'CL', 'CHL', 'CLP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (49, 'China', 'https://flagcdn.com/cn.svg', '86', 'CN', 'CHN', 'CNY') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (50, 'Christmas Island', 'https://flagcdn.com/cx.svg', '61', 'CX', 'CXR', 'AUD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (51, 'Cocos (Keeling) Islands', 'https://flagcdn.com/cc.svg', '61', 'CC', 'CCK', 'AUD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (52, 'Colombia', 'https://flagcdn.com/co.svg', '57', 'CO', 'COL', 'COP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (53, 'Comoros', 'https://flagcdn.com/km.svg', '269', 'KM', 'COM', 'KMF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (54, 'Congo', 'https://flagcdn.com/cg.svg', '242', 'CG', 'COG', 'XAF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (55, 'Congo (Democratic Republic of the)', 'https://flagcdn.com/cd.svg', '243', 'CD', 'COD', 'CDF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (56, 'Cook Islands', 'https://flagcdn.com/ck.svg', '682', 'CK', 'COK', 'NZD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (57, 'Costa Rica', 'https://flagcdn.com/cr.svg', '506', 'CR', 'CRI', 'CRC') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (58, 'Croatia', 'https://flagcdn.com/hr.svg', '385', 'HR', 'HRV', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (59, 'Cuba', 'https://flagcdn.com/cu.svg', '53', 'CU', 'CUB', 'CUP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (60, 'Curaçao', 'https://flagcdn.com/cw.svg', '599', 'CW', 'CUW', 'ANG') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (61, 'Cyprus', 'https://flagcdn.com/cy.svg', '357', 'CY', 'CYP', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (62, 'Czech Republic', 'https://flagcdn.com/cz.svg', '420', 'CZ', 'CZE', 'CZK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (63, 'Denmark', 'https://flagcdn.com/dk.svg', '45', 'DK', 'DNK', 'DKK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (64, 'Djibouti', 'https://flagcdn.com/dj.svg', '253', 'DJ', 'DJI', 'DJF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (65, 'Dominica', 'https://flagcdn.com/dm.svg', '1', 'DM', 'DMA', 'XCD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (66, 'Dominican Republic', 'https://flagcdn.com/do.svg', '1', 'DO', 'DOM', 'DOP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (67, 'Ecuador', 'https://flagcdn.com/ec.svg', '593', 'EC', 'ECU', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (68, 'Egypt', 'https://flagcdn.com/eg.svg', '20', 'EG', 'EGY', 'EGP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (69, 'El Salvador', 'https://flagcdn.com/sv.svg', '503', 'SV', 'SLV', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (70, 'Equatorial Guinea', 'https://flagcdn.com/gq.svg', '240', 'GQ', 'GNQ', 'XAF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (71, 'Eritrea', 'https://flagcdn.com/er.svg', '291', 'ER', 'ERI', 'ERN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (72, 'Estonia', 'https://flagcdn.com/ee.svg', '372', 'EE', 'EST', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (73, 'Ethiopia', 'https://flagcdn.com/et.svg', '251', 'ET', 'ETH', 'ETB') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (74, 'Falkland Islands (Malvinas)', 'https://flagcdn.com/fk.svg', '500', 'FK', 'FLK', 'FKP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (75, 'Faroe Islands', 'https://flagcdn.com/fo.svg', '298', 'FO', 'FRO', 'DKK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (76, 'Fiji', 'https://flagcdn.com/fj.svg', '679', 'FJ', 'FJI', 'FJD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (77, 'Finland', 'https://flagcdn.com/fi.svg', '358', 'FI', 'FIN', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (78, 'France', 'https://flagcdn.com/fr.svg', '33', 'FR', 'FRA', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (79, 'French Guiana', 'https://flagcdn.com/gf.svg', '594', 'GF', 'GUF', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (80, 'French Polynesia', 'https://flagcdn.com/pf.svg', '689', 'PF', 'PYF', 'XPF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (81, 'French Southern Territories', 'https://flagcdn.com/tf.svg', '262', 'TF', 'ATF', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (82, 'Gabon', 'https://flagcdn.com/ga.svg', '241', 'GA', 'GAB', 'XAF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (83, 'Gambia', 'https://flagcdn.com/gm.svg', '220', 'GM', 'GMB', 'GMD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (84, 'Georgia', 'https://flagcdn.com/ge.svg', '995', 'GE', 'GEO', 'GEL') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (85, 'Germany', 'https://flagcdn.com/de.svg', '49', 'DE', 'DEU', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (86, 'Ghana', 'https://flagcdn.com/gh.svg', '233', 'GH', 'GHA', 'GHS') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (87, 'Gibraltar', 'https://flagcdn.com/gi.svg', '350', 'GI', 'GIB', 'GIP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (88, 'Greece', 'https://flagcdn.com/gr.svg', '30', 'GR', 'GRC', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (89, 'Greenland', 'https://flagcdn.com/gl.svg', '299', 'GL', 'GRL', 'DKK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (90, 'Grenada', 'https://flagcdn.com/gd.svg', '1', 'GD', 'GRD', 'XCD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (91, 'Guadeloupe', 'https://flagcdn.com/gp.svg', '590', 'GP', 'GLP', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (92, 'Guam', 'https://flagcdn.com/gu.svg', '1', 'GU', 'GUM', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (93, 'Guatemala', 'https://flagcdn.com/gt.svg', '502', 'GT', 'GTM', 'GTQ') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (94, 'Guernsey', 'https://flagcdn.com/gg.svg', '44', 'GG', 'GGY', 'GBP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (95, 'Guinea', 'https://flagcdn.com/gn.svg', '224', 'GN', 'GIN', 'GNF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (96, 'Guinea-Bissau', 'https://flagcdn.com/gw.svg', '245', 'GW', 'GNB', 'XOF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (97, 'Guyana', 'https://flagcdn.com/gy.svg', '592', 'GY', 'GUY', 'GYD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (98, 'Haiti', 'https://flagcdn.com/ht.svg', '509', 'HT', 'HTI', 'HTG') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (99, 'Heard Island and McDonald Islands', 'https://flagcdn.com/hm.svg', '672', 'HM', 'HMD', 'AUD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (100, 'Vatican City', 'https://flagcdn.com/va.svg', '379', 'VA', 'VAT', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (101, 'Honduras', 'https://flagcdn.com/hn.svg', '504', 'HN', 'HND', 'HNL') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (102, 'Hungary', 'https://flagcdn.com/hu.svg', '36', 'HU', 'HUN', 'HUF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (103, 'Hong Kong', 'https://flagcdn.com/hk.svg', '852', 'HK', 'HKG', 'HKD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (104, 'Iceland', 'https://flagcdn.com/is.svg', '354', 'IS', 'ISL', 'ISK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (105, 'India', 'https://flagcdn.com/in.svg', '91', 'IN', 'IND', 'INR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (106, 'Indonesia', 'https://flagcdn.com/id.svg', '62', 'ID', 'IDN', 'IDR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (107, 'Ivory Coast', 'https://flagcdn.com/ci.svg', '225', 'CI', 'CIV', 'XOF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (108, 'Iran (Islamic Republic of)', 'https://flagcdn.com/ir.svg', '98', 'IR', 'IRN', 'IRR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (109, 'Iraq', 'https://flagcdn.com/iq.svg', '964', 'IQ', 'IRQ', 'IQD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (110, 'Ireland', 'https://flagcdn.com/ie.svg', '353', 'IE', 'IRL', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (111, 'Isle of Man', 'https://flagcdn.com/im.svg', '44', 'IM', 'IMN', 'GBP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (112, 'Israel', 'https://flagcdn.com/il.svg', '972', 'IL', 'ISR', 'ILS') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (113, 'Italy', 'https://flagcdn.com/it.svg', '39', 'IT', 'ITA', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (114, 'Jamaica', 'https://flagcdn.com/jm.svg', '1', 'JM', 'JAM', 'JMD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (115, 'Japan', 'https://flagcdn.com/jp.svg', '81', 'JP', 'JPN', 'JPY') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (116, 'Jersey', 'https://flagcdn.com/je.svg', '44', 'JE', 'JEY', 'GBP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (117, 'Jordan', 'https://flagcdn.com/jo.svg', '962', 'JO', 'JOR', 'JOD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (118, 'Kazakhstan', 'https://flagcdn.com/kz.svg', '76', 'KZ', 'KAZ', 'KZT') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (119, 'Kenya', 'https://flagcdn.com/ke.svg', '254', 'KE', 'KEN', 'KES') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (120, 'Kiribati', 'https://flagcdn.com/ki.svg', '686', 'KI', 'KIR', 'AUD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (121, 'Kuwait', 'https://flagcdn.com/kw.svg', '965', 'KW', 'KWT', 'KWD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (122, 'Kyrgyzstan', 'https://flagcdn.com/kg.svg', '996', 'KG', 'KGZ', 'KGS') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (123, 'Lao People''s Democratic Republic', 'https://flagcdn.com/la.svg', '856', 'LA', 'LAO', 'LAK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (124, 'Latvia', 'https://flagcdn.com/lv.svg', '371', 'LV', 'LVA', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (125, 'Lebanon', 'https://flagcdn.com/lb.svg', '961', 'LB', 'LBN', 'LBP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (126, 'Lesotho', 'https://flagcdn.com/ls.svg', '266', 'LS', 'LSO', 'LSL') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (127, 'Liberia', 'https://flagcdn.com/lr.svg', '231', 'LR', 'LBR', 'LRD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (128, 'Libya', 'https://flagcdn.com/ly.svg', '218', 'LY', 'LBY', 'LYD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (129, 'Liechtenstein', 'https://flagcdn.com/li.svg', '423', 'LI', 'LIE', 'CHF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (130, 'Lithuania', 'https://flagcdn.com/lt.svg', '370', 'LT', 'LTU', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (131, 'Luxembourg', 'https://flagcdn.com/lu.svg', '352', 'LU', 'LUX', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (132, 'Macao', 'https://flagcdn.com/mo.svg', '853', 'MO', 'MAC', 'MOP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (133, 'North Macedonia', 'https://flagcdn.com/mk.svg', '389', 'MK', 'MKD', 'MKD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (134, 'Madagascar', 'https://flagcdn.com/mg.svg', '261', 'MG', 'MDG', 'MGA') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (135, 'Malawi', 'https://flagcdn.com/mw.svg', '265', 'MW', 'MWI', 'MWK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (136, 'Malaysia', 'https://flagcdn.com/my.svg', '60', 'MY', 'MYS', 'MYR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (137, 'Maldives', 'https://flagcdn.com/mv.svg', '960', 'MV', 'MDV', 'MVR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (138, 'Mali', 'https://flagcdn.com/ml.svg', '223', 'ML', 'MLI', 'XOF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (139, 'Malta', 'https://flagcdn.com/mt.svg', '356', 'MT', 'MLT', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (140, 'Marshall Islands', 'https://flagcdn.com/mh.svg', '692', 'MH', 'MHL', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (141, 'Martinique', 'https://flagcdn.com/mq.svg', '596', 'MQ', 'MTQ', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (142, 'Mauritania', 'https://flagcdn.com/mr.svg', '222', 'MR', 'MRT', 'MRU') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (143, 'Mauritius', 'https://flagcdn.com/mu.svg', '230', 'MU', 'MUS', 'MUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (144, 'Mayotte', 'https://flagcdn.com/yt.svg', '262', 'YT', 'MYT', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (145, 'Mexico', 'https://flagcdn.com/mx.svg', '52', 'MX', 'MEX', 'MXN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (146, 'Micronesia (Federated States of)', 'https://flagcdn.com/fm.svg', '691', 'FM', 'FSM', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (147, 'Moldova (Republic of)', 'https://flagcdn.com/md.svg', '373', 'MD', 'MDA', 'MDL') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (148, 'Monaco', 'https://flagcdn.com/mc.svg', '377', 'MC', 'MCO', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (149, 'Mongolia', 'https://flagcdn.com/mn.svg', '976', 'MN', 'MNG', 'MNT') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (150, 'Montenegro', 'https://flagcdn.com/me.svg', '382', 'ME', 'MNE', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (151, 'Montserrat', 'https://flagcdn.com/ms.svg', '1', 'MS', 'MSR', 'XCD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (152, 'Morocco', 'https://flagcdn.com/ma.svg', '212', 'MA', 'MAR', 'MAD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (153, 'Mozambique', 'https://flagcdn.com/mz.svg', '258', 'MZ', 'MOZ', 'MZN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (154, 'Myanmar', 'https://flagcdn.com/mm.svg', '95', 'MM', 'MMR', 'MMK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (155, 'Namibia', 'https://flagcdn.com/na.svg', '264', 'NA', 'NAM', 'NAD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (156, 'Nauru', 'https://flagcdn.com/nr.svg', '674', 'NR', 'NRU', 'AUD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (157, 'Nepal', 'https://flagcdn.com/np.svg', '977', 'NP', 'NPL', 'NPR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (158, 'Netherlands', 'https://flagcdn.com/nl.svg', '31', 'NL', 'NLD', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (159, 'New Caledonia', 'https://flagcdn.com/nc.svg', '687', 'NC', 'NCL', 'XPF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (160, 'New Zealand', 'https://flagcdn.com/nz.svg', '64', 'NZ', 'NZL', 'NZD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (161, 'Nicaragua', 'https://flagcdn.com/ni.svg', '505', 'NI', 'NIC', 'NIO') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (162, 'Niger', 'https://flagcdn.com/ne.svg', '227', 'NE', 'NER', 'XOF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (163, 'Nigeria', 'https://flagcdn.com/ng.svg', '234', 'NG', 'NGA', 'NGN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (164, 'Niue', 'https://flagcdn.com/nu.svg', '683', 'NU', 'NIU', 'NZD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (165, 'Norfolk Island', 'https://flagcdn.com/nf.svg', '672', 'NF', 'NFK', 'AUD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (166, 'Korea (Democratic People''s Republic of)', 'https://flagcdn.com/kp.svg', '850', 'KP', 'PRK', 'KPW') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (167, 'Northern Mariana Islands', 'https://flagcdn.com/mp.svg', '1', 'MP', 'MNP', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (168, 'Norway', 'https://flagcdn.com/no.svg', '47', 'NO', 'NOR', 'NOK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (169, 'Oman', 'https://flagcdn.com/om.svg', '968', 'OM', 'OMN', 'OMR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (170, 'Pakistan', 'https://flagcdn.com/pk.svg', '92', 'PK', 'PAK', 'PKR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (171, 'Palau', 'https://flagcdn.com/pw.svg', '680', 'PW', 'PLW', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (172, 'Palestine, State of', 'https://flagcdn.com/ps.svg', '970', 'PS', 'PSE', 'ILS') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (173, 'Panama', 'https://flagcdn.com/pa.svg', '507', 'PA', 'PAN', 'PAB') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (174, 'Papua New Guinea', 'https://flagcdn.com/pg.svg', '675', 'PG', 'PNG', 'PGK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (175, 'Paraguay', 'https://flagcdn.com/py.svg', '595', 'PY', 'PRY', 'PYG') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (176, 'Peru', 'https://flagcdn.com/pe.svg', '51', 'PE', 'PER', 'PEN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (177, 'Philippines', 'https://flagcdn.com/ph.svg', '63', 'PH', 'PHL', 'PHP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (178, 'Pitcairn', 'https://flagcdn.com/pn.svg', '64', 'PN', 'PCN', 'NZD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (179, 'Poland', 'https://flagcdn.com/pl.svg', '48', 'PL', 'POL', 'PLN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (180, 'Portugal', 'https://flagcdn.com/pt.svg', '351', 'PT', 'PRT', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (181, 'Puerto Rico', 'https://flagcdn.com/pr.svg', '1', 'PR', 'PRI', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (182, 'Qatar', 'https://flagcdn.com/qa.svg', '974', 'QA', 'QAT', 'QAR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (183, 'Republic of Kosovo', 'https://flagcdn.com/xk.svg', '383', 'XK', 'UNK', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (184, 'Réunion', 'https://flagcdn.com/re.svg', '262', 'RE', 'REU', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (185, 'Romania', 'https://flagcdn.com/ro.svg', '40', 'RO', 'ROU', 'RON') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (186, 'Russian Federation', 'https://flagcdn.com/ru.svg', '7', 'RU', 'RUS', 'RUB') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (187, 'Rwanda', 'https://flagcdn.com/rw.svg', '250', 'RW', 'RWA', 'RWF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (188, 'Saint Barthélemy', 'https://flagcdn.com/bl.svg', '590', 'BL', 'BLM', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (189, 'Saint Helena, Ascension and Tristan da Cunha', 'https://flagcdn.com/sh.svg', '290', 'SH', 'SHN', 'SHP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (190, 'Saint Kitts and Nevis', 'https://flagcdn.com/kn.svg', '1', 'KN', 'KNA', 'XCD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (191, 'Saint Lucia', 'https://flagcdn.com/lc.svg', '1', 'LC', 'LCA', 'XCD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (192, 'Saint Martin (French part)', 'https://flagcdn.com/mf.svg', '590', 'MF', 'MAF', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (193, 'Saint Pierre and Miquelon', 'https://flagcdn.com/pm.svg', '508', 'PM', 'SPM', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (194, 'Saint Vincent and the Grenadines', 'https://flagcdn.com/vc.svg', '1', 'VC', 'VCT', 'XCD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (195, 'Samoa', 'https://flagcdn.com/ws.svg', '685', 'WS', 'WSM', 'WST') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (196, 'San Marino', 'https://flagcdn.com/sm.svg', '378', 'SM', 'SMR', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (197, 'Sao Tome and Principe', 'https://flagcdn.com/st.svg', '239', 'ST', 'STP', 'STN') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (198, 'Saudi Arabia', 'https://flagcdn.com/sa.svg', '966', 'SA', 'SAU', 'SAR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (199, 'Senegal', 'https://flagcdn.com/sn.svg', '221', 'SN', 'SEN', 'XOF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (200, 'Serbia', 'https://flagcdn.com/rs.svg', '381', 'RS', 'SRB', 'RSD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (201, 'Seychelles', 'https://flagcdn.com/sc.svg', '248', 'SC', 'SYC', 'SCR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (202, 'Sierra Leone', 'https://flagcdn.com/sl.svg', '232', 'SL', 'SLE', 'SLE') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (203, 'Singapore', 'https://flagcdn.com/sg.svg', '65', 'SG', 'SGP', 'SGD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (204, 'Sint Maarten (Dutch part)', 'https://flagcdn.com/sx.svg', '1', 'SX', 'SXM', 'ANG') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (205, 'Slovakia', 'https://flagcdn.com/sk.svg', '421', 'SK', 'SVK', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (206, 'Slovenia', 'https://flagcdn.com/si.svg', '386', 'SI', 'SVN', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (207, 'Solomon Islands', 'https://flagcdn.com/sb.svg', '677', 'SB', 'SLB', 'SBD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (208, 'Somalia', 'https://flagcdn.com/so.svg', '252', 'SO', 'SOM', 'SOS') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (209, 'South Africa', 'https://flagcdn.com/za.svg', '27', 'ZA', 'ZAF', 'ZAR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (210, 'South Georgia and the South Sandwich Islands', 'https://flagcdn.com/gs.svg', '500', 'GS', 'SGS', 'GBP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (211, 'Korea (Republic of)', 'https://flagcdn.com/kr.svg', '82', 'KR', 'KOR', 'KRW') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (212, 'Spain', 'https://flagcdn.com/es.svg', '34', 'ES', 'ESP', 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (213, 'Sri Lanka', 'https://flagcdn.com/lk.svg', '94', 'LK', 'LKA', 'LKR') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (214, 'Sudan', 'https://flagcdn.com/sd.svg', '249', 'SD', 'SDN', 'SDG') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (215, 'South Sudan', 'https://flagcdn.com/ss.svg', '211', 'SS', 'SSD', 'SSP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (216, 'Suriname', 'https://flagcdn.com/sr.svg', '597', 'SR', 'SUR', 'SRD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (217, 'Svalbard and Jan Mayen', 'https://flagcdn.com/sj.svg', '47', 'SJ', 'SJM', 'NOK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (218, 'Swaziland', 'https://flagcdn.com/sz.svg', '268', 'SZ', 'SWZ', 'SZL') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (219, 'Sweden', 'https://flagcdn.com/se.svg', '46', 'SE', 'SWE', 'SEK') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (220, 'Switzerland', 'https://flagcdn.com/ch.svg', '41', 'CH', 'CHE', 'CHF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (221, 'Syrian Arab Republic', 'https://flagcdn.com/sy.svg', '963', 'SY', 'SYR', 'SYP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (222, 'Taiwan', 'https://flagcdn.com/tw.svg', '886', 'TW', 'TWN', 'TWD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (223, 'Tajikistan', 'https://flagcdn.com/tj.svg', '992', 'TJ', 'TJK', 'TJS') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (224, 'Tanzania, United Republic of', 'https://flagcdn.com/tz.svg', '255', 'TZ', 'TZA', 'TZS') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (225, 'Thailand', 'https://flagcdn.com/th.svg', '66', 'TH', 'THA', 'THB') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (226, 'Timor-Leste', 'https://flagcdn.com/tl.svg', '670', 'TL', 'TLS', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (227, 'Togo', 'https://flagcdn.com/tg.svg', '228', 'TG', 'TGO', 'XOF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (228, 'Tokelau', 'https://flagcdn.com/tk.svg', '690', 'TK', 'TKL', 'NZD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (229, 'Tonga', 'https://flagcdn.com/to.svg', '676', 'TO', 'TON', 'TOP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (230, 'Trinidad and Tobago', 'https://flagcdn.com/tt.svg', '1', 'TT', 'TTO', 'TTD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (231, 'Tunisia', 'https://flagcdn.com/tn.svg', '216', 'TN', 'TUN', 'TND') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (232, 'Turkey', 'https://flagcdn.com/tr.svg', '90', 'TR', 'TUR', 'TRY') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (233, 'Turkmenistan', 'https://flagcdn.com/tm.svg', '993', 'TM', 'TKM', 'TMT') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (234, 'Turks and Caicos Islands', 'https://flagcdn.com/tc.svg', '1', 'TC', 'TCA', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (235, 'Tuvalu', 'https://flagcdn.com/tv.svg', '688', 'TV', 'TUV', 'AUD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (236, 'Uganda', 'https://flagcdn.com/ug.svg', '256', 'UG', 'UGA', 'UGX') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (237, 'Ukraine', 'https://flagcdn.com/ua.svg', '380', 'UA', 'UKR', 'UAH') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (238, 'United Arab Emirates', 'https://flagcdn.com/ae.svg', '971', 'AE', 'ARE', 'AED') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (239, 'United Kingdom of Great Britain and Northern Ireland', 'https://flagcdn.com/gb.svg', '44', 'GB', 'GBR', 'GBP') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (240, 'United States of America', 'https://flagcdn.com/us.svg', '1', 'US', 'USA', 'USD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (241, 'Uruguay', 'https://flagcdn.com/uy.svg', '598', 'UY', 'URY', 'UYU') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (242, 'Uzbekistan', 'https://flagcdn.com/uz.svg', '998', 'UZ', 'UZB', 'UZS') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (243, 'Vanuatu', 'https://flagcdn.com/vu.svg', '678', 'VU', 'VUT', 'VUV') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (244, 'Venezuela (Bolivarian Republic of)', 'https://flagcdn.com/ve.svg', '58', 'VE', 'VEN', 'VES') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (245, 'Vietnam', 'https://flagcdn.com/vn.svg', '84', 'VN', 'VNM', 'VND') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (246, 'Wallis and Futuna', 'https://flagcdn.com/wf.svg', '681', 'WF', 'WLF', 'XPF') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (247, 'Western Sahara', 'https://flagcdn.com/eh.svg', '212', 'EH', 'ESH', 'MAD') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (248, 'Yemen', 'https://flagcdn.com/ye.svg', '967', 'YE', 'YEM', 'YER') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (249, 'Zambia', 'https://flagcdn.com/zm.svg', '260', 'ZM', 'ZMB', 'ZMW') ON CONFLICT DO NOTHING;
INSERT INTO payment."Country" ("Id", "Name", "FlagUrl", "DialCode", "Alpha2Code", "Alpha3Code", "CurrencyCode") VALUES (250, 'Zimbabwe', 'https://flagcdn.com/zw.svg', '263', 'ZW', 'ZWE', 'ZWL') ON CONFLICT DO NOTHING;
